// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	CreateVideoCategory(ctx context.Context, arg CreateVideoCategoryParams) (VideoCategory, error)
	GetCategory(ctx context.Context, videoCategoryName string) (VideoCategory, error)
}

var _ Querier = (*Queries)(nil)
