// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: video.sql

package db

import (
	"context"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    video_category_name,
                    code,
    name,
    url,
    created_at
) VALUES (
             $1, $2, $3, $4, DEFAULT
         )
    RETURNING video_id, video_category_name, code, name, url, created_at
`

type CreateVideoParams struct {
	VideoCategoryName string `json:"video_category_name"`
	Code              string `json:"code"`
	Name              string `json:"name"`
	Url               string `json:"url"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.VideoCategoryName,
		arg.Code,
		arg.Name,
		arg.Url,
	)
	var i Video
	err := row.Scan(
		&i.VideoID,
		&i.VideoCategoryName,
		&i.Code,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVideoByID = `-- name: DeleteVideoByID :exec
DELETE FROM videos
WHERE video_id = $1
`

func (q *Queries) DeleteVideoByID(ctx context.Context, videoID int64) error {
	_, err := q.db.Exec(ctx, deleteVideoByID, videoID)
	return err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT video_id, video_category_name, code, name, url, created_at FROM videos
WHERE video_id = $1
`

func (q *Queries) GetVideoByID(ctx context.Context, videoID int64) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, videoID)
	var i Video
	err := row.Scan(
		&i.VideoID,
		&i.VideoCategoryName,
		&i.Code,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT video_id, video_category_name, code, name, url, created_at
FROM videos
ORDER BY
    CASE WHEN $1::text = 'video_id' AND $2::text = 'asc' THEN video_id END ASC NULLS LAST,
    CASE WHEN $1::text = 'video_id' AND $2::text = 'desc' THEN video_id END DESC NULLS LAST,
    CASE WHEN $1::text = 'video_category_name' AND $2::text = 'asc' THEN video_category_name END ASC NULLS LAST,
    CASE WHEN $1::text = 'video_category_name' AND $2::text = 'desc' THEN video_category_name END DESC NULLS LAST,
    CASE WHEN $1::text = 'created_at' AND $2::text = 'asc' THEN created_at END ASC NULLS LAST,
    CASE WHEN $1::text = 'created_at' AND $2::text = 'desc' THEN created_at END DESC NULLS LAST
LIMIT $3
OFFSET $4
`

type ListVideosParams struct {
	OrderBy     string `json:"order_by"`
	OrderDir    string `json:"order_dir"`
	LimitCount  int32  `json:"limit_count"`
	OffsetCount int32  `json:"offset_count"`
}

func (q *Queries) ListVideos(ctx context.Context, arg ListVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos, arg.OrderBy, arg.OrderDir, arg.LimitCount, arg.OffsetCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.VideoID,
			&i.VideoCategoryName,
			&i.Code,
			&i.Name,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
